# servers/retriever/parameter.yaml

model_name_or_path: openbmb/MiniCPM-Embedding-Light
corpus_path: data/corpus_example.jsonl
embedding_path: embedding/embedding.npy
index_path: index/index.index

backend: infinity # options: infinity, sentencetransformers, openai
backend_configs:
  infinity:
    bettertransformer: false
    pooling_method: auto
    device: cuda
    model_warmup: false
    trust_remote_code: true
  sentencetransformers:
    device: cuda
    trust_remote_code: true
  openai:
    openai_model: text-embedding-3-small
    api_base: "https://api.openai.com/v1"
    api_key: ""
  sentencetransformers_encode:
    normalize_embeddings: false

batch_size: 16
top_k: 5
cuda_devices: "2,3"
query_instruction: "Query: "
is_multimodal: false
faiss_use_gpu: True
overwrite: false
retriever_url: http://localhost:8080
index_chunk_size: 50000
